name: CI/CD - Core Prod

run-name: 'Deployment: Core Prod by @${{ github.actor }}'

on:
  workflow_dispatch:
  push:
    branches:    
      - main
    paths:
      - 'apps/api/**'

env:
  IMAGE_URL: registry.digitalocean.com/silver-registry/core-sales:latest

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
     
      - name: Build container image
        run: docker build -f docker/core/prod.dockerfile -t ${{ env.IMAGE_URL }} .

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
      
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.IMAGE_URL }}
      