export const SENIORITIES = ['JR', 'SSR', 'SR', 'STAFF', 'MANAGER', 'C-LEVEL']

export const COMPANY_SIZES = {
  SELF_EMPLOYED: 'Self-employed',
  ONE_TO_TEN: '1-10',
  ELEVEN_TO_FIFTY: '11-50',
  FIFTY_ONE_TO_TWO_HUNDRED: '51-200',
  TWO_HUNDRED_ONE_TO_FIVE_HUNDRED: '201-500',
  FIVE_HUNDRED_ONE_TO_ONE_THOUSAND: '501-1000',
  ONE_THOUSAND_ONE_TO_FIVE_THOUSAND: '1001-5000',
}

export const LANGUAGES = ['en', 'es', 'fr', 'it']
